version: '3.8'

services:

  wsmonitor:
    build: .
    command: python3 websocket-monitor.py
    container_name: wsmonitor
    environment:
      PYTHONUNBUFFERED: 'true'
    env_file:
      - '.env'
    restart: always
    networks_mode: host